### ISSUE TITLE
Clarification needed to describe the differences with P2P-RPL

### ISSUE THREAD

**Issue by inesrob** [roll-wg/aodv-rpl#5]
From

"AODV-RPL uses the "P2P Route Discovery Mode of Operation" (MOP == 4) with
   three new Options for the DIO message, dedicated to discover P2P
   routes.  These P2P routes may differ from routes discoverable by
   native RPL.  Since AODV-RPL uses newly defined Options, there is no
   conflict with P2P-RPL [[RFC6997](https://datatracker.ietf.org/doc/html/rfc6997)], a previous document using the same
   MOP."

It is not clear how the newly defined options (which ones?) do not conflict with P2P-RPL. Please add more clarification.

**Comment by charliep51** [comment]
This issue has been resolved by requesting IANA to allocate a new multicast group for the use of nodes implementing AODV-RPL.  The newly defined options are AODV-RPL RREQ, AODV-RPL RREP, and AODV-RPL Target (ART).

**Comment by charliep51** [comment]
With this resolution, I believe the issue can be closed.
